name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests and Collect Coverage
        run: npm run test

      - name: Run Cypress Tests and Collect Coverage
        run: npm run cypress:run
        # Ustaw ścieżkę do Twojego skryptu uruchamiającego Cypress z opcją zbierania code coverage
